"""Add column is_vaccinated

Revision ID: 6c563f045a48
Revises: c3718820fd72
Create Date: 2023-12-21 20:25:20.103739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c563f045a48'
down_revision: Union[str, None] = 'c3718820fd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column('pets',sa.Column('is_vaccinated',sa.Boolean(),default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets','is_vaccinated')
    # ### end Alembic commands ###
