"""Initial

Revision ID: c3718820fd72
Revises: 
Create Date: 2023-12-21 19:48:33.496969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3718820fd72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('petId', sa.String(), nullable=False),
    sa.Column('petName', sa.String(), nullable=True),
    sa.Column('petBreed', sa.String(), nullable=True),
    sa.Column('petAge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('petId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
